CREATE DATABASE `hibernate_schema` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci
CREATE  TABLE `hibernate_schema`.`PERSON` (
  `UNIQUE_ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `SECOND_NAME` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`UNIQUE_ID`) );
CREATE  TABLE `hibernate_schema`.`ADDRESS` (
  `UNIQUE_ID` INT NOT NULL ,
  `FIRST_LINE` VARCHAR(45) NOT NULL ,
  `SECOND_LINE` VARCHAR(45) NULL ,
  `POSTCODE` VARCHAR(45) NULL ,
  PRIMARY KEY (`UNIQUE_ID`) ,
  INDEX `FK_PERSON_UNIQUE_ID` (`UNIQUE_ID` ASC) ,
  CONSTRAINT `FK_PERSON_UNIQUE_ID`
    FOREIGN KEY (`UNIQUE_ID` )
    REFERENCES `hibernate_schema`.`PERSON` (`UNIQUE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);